import Navbar from "../Navbar/Navbar"
import Footer from "../Footer/Footer"
import Head from "next/head"
 

import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

import {SessionProvider} from 'next-auth/react';

export default function Layout({children}){
  return (
    <>
    <Head>
        <title>BrainlyMCQs.com</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="google" content="notranslate" />
        <meta name="robots" content="index, follow" />
  <meta property="og:title" content="My awesome website" />
  <meta property="og:description" content="My website description" />
  <meta property="og:image" content="/images/og-image.jpg" />
  <meta property="og:url" content="https://www.example.com" />
  <meta property="og:type" content="website" />
  <meta property="twitter:card" content="summary_large_image" />
  <meta property="twitter:title" content="My awesome website" />
  <meta property="twitter:description" content="My website description" />
  <meta property="twitter:image" content="/images/twitter-card-image.jpg" />
  <meta property="twitter:url" content="https://www.example.com" />

      </Head>
      <Navbar />
      
<ToastContainer
position="top-right"
autoClose={4000}
hideProgressBar={false}
newestOnTop={false}
closeOnClick
rtl={false}
pauseOnFocusLoss
draggable
pauseOnHover
theme="light"
/>
        <main>{children}</main>
        
      <Footer/>
    </>
  )
}
